name       : gource
version    : '0.49'
release    : 8
source     :
    - https://github.com/acaudwell/Gource/releases/download/gource-0.49/gource-0.49.tar.gz : a9dd23693861e224322708a8e26c9e3aaa3e4c9ec41264b1ee2d5dcd6e2c0e8a
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Software version control visualization
description: |
    OpenGL-based 3D visualisation tool for source control repositories.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(libpcre)
    - pkgconfig(sdl)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
