name       : gource
version    : 0.44
release    : 1
source     :
    - https://github.com/acaudwell/Gource/releases/download/gource-0.44/gource-0.44.tar.gz : 2604ca4442305ffdc5bb1a7bac07e223d59c846f93567be067e8dfe2f42f097c
license    : GPL-3.0
component  : programming.tools
summary    : Software version control visualization 
description: |
    OpenGL-based 3D visualisation tool for source control repositories.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpcre)
    - pkgconfig(libpng)
    - pkgconfig(sdl)
    - pkgconfig(SDL2_image)
    - glm
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
