name       : gource
version    : '0.47'
release    : 3
source     :
    - https://github.com/acaudwell/Gource/releases/download/gource-0.47/gource-0.47.tar.gz : f2b16083a01b897b6c062b363793028fb9e01cd6f888d91772ee06e56ce398d2
license    : GPL-3.0
component  : programming.tools
summary    : Software version control visualization
description: |
    OpenGL-based 3D visualisation tool for source control repositories.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(glm)
    - pkgconfig(libpcre)
    - pkgconfig(libpng)
    - pkgconfig(sdl)
    - pkgconfig(SDL2_image)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
